services:
  pat-mat_db:
    container_name: pat-mat_db
    image: postgres:14.3-alpine
    restart: unless-stopped
    volumes:
      - ./backend_db:/var/lib/postgresql/data
    env_file:
      - .env

  pat-mat_api:
    container_name: pat-mat_api
    build: .
    restart: unless-stopped
    depends_on:
      - pat-mat_db
    volumes:
      - .:/app
    ports:
      - 9062:80
    env_file:
      - .env

  # backend_worker:
  #   container_name: backend_worker
  #   build: .
  #   working_dir: /app/pat-mat
  #   command: ["celery", "-A", "pat-mat", "worker", "-l", "info"]
  #   restart: unless-stopped
  #   volumes:
  #     - .:/app
  #   depends_on:
  #     - backend_db
  #     - backend_redis
  #   env_file:
  #     - .env

  # backend_beat:
  #   container_name: backend_beat
  #   build: .
  #   working_dir: /app/pat-mat
  #   command: ["celery", "-A", "pat-mat", "beat", "-l", "info"]
  #   restart: unless-stopped
  #   volumes:
  #     - .:/app
  #   depends_on:
  #     - backend_db
  #     - backend_redis
  #   env_file:
  #     - .env

  # backend_redis:
  #   container_name : backend_redis
  #   image: redis:6.2-alpine
  #   restart: unless-stopped
